name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: read environment file
        run: cat hadoop.env >>${GITHUB_ENV}   
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: palashkulsh/hadoop-base:latest
